# Generated by Django 4.2.11 on 2025-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True),
        ),
    ]
