# Generated by Django 4.2.11 on 2025-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.IntegerField(default=30, help_text='Duração em minutos'),
        ),
    ]
