# Generated by Django 4.2.11 on 2025-07-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='responsavel',
        ),
        migrations.DeleteModel(
            name='DisponibilidadeAgenda',
        ),
    ]
