# Generated by Django 4.2.11 on 2025-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_crmv_usuario_especialidade_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
