# Generated by Django 4.2.20 on 2025-05-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='admins',
            field=models.ManyToManyField(related_name='empresas_administradas', to='usuarios.usuario'),
        ),
    ]
