# Generated by Django 4.2.11 on 2025-07-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaobrand_usuario_alter_empresa_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('usuarios', 'Usuários'), ('agendamentos', 'Agendamentos'), ('animais', 'Animais'), ('servicos', 'Serviços'), ('configuracoes', 'Configurações'), ('relatorios', 'Relatórios'), ('brand', 'Marca/Branding')], help_text='Recurso sobre o qual a permissão se aplica', max_length=50)),
                ('action', models.CharField(choices=[('create', 'Criar'), ('read', 'Visualizar'), ('update', 'Editar'), ('delete', 'Excluir'), ('list', 'Listar'), ('manage', 'Gerenciar')], help_text='Ação permitida sobre o recurso', max_length=20)),
                ('description', models.CharField(help_text='Descrição clara da permissão', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['resource', 'action'],
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único do role (ex: admin, veterinario, recepcionista)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Nome amigável para exibição (ex: Administrador, Veterinário)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição das responsabilidades deste role', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se este role está ativo e pode ser atribuído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se esta atribuição está ativa')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Usuário que atribuiu este role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to='core.usuario')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Role do Usuário',
                'verbose_name_plural': 'Roles dos Usuários',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Usuário que concedeu esta permissão', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
            ],
            options={
                'verbose_name': 'Permissão do Role',
                'verbose_name_plural': 'Permissões dos Roles',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
